### ISSUE TITLE
عقب خوردن تاریخ

### ISSUE THREAD

**Issue by SHAliakbari** [mrmashal/angular-material-persian-datepicker#2]
سلام
در اولین بار که فرم باز میشه و تاریخی انتخاب میشه در مدل انتصاب داده شده یک روز عقب تر ست میشه
مثلا تاریخ 1396/09/17 که معادل تقویم میلادی اون میشه 2017-12-08 هست رو اگر توسط تقویم کامپوننت انتخاب کنیم در model مربوطه مقدار 2017-12-07 ذخیره میشه .
در اجرا های بعدی (یعنی دفعه بعدی که در لود فرم مقداری در model وجود داره) همه چیز درسته و مشکلی نیست فقط در اولین بار این مشکل وجود داره

**Comment by mrmashal** [comment]
سلام. نتونستم بازتولید کنم خطا رو. لطفا مطمئن شید آخرین نسخه رو دارید و در صورت وجود خطا، نمونه قابل بررسی بگذارید. ممنون

**Comment by mrmashal** [comment]
احتمالا مشکل مشابه #3 باشه
