### ISSUE TITLE
تاریخ یک روز عقب است

### ISSUE THREAD

**Issue by KarimFereidooni** [mrmashal/angular-material-persian-datepicker#3]
تاریخی شمسی که در کامپوننت نمایش داده می شود درست است اما تاریخ میلادی که به مدل داده می شود یکروز عقب است
بعنوان مثال وقتی 1396/11/18 انتخاب می شود
مقدار
2018-02-06T20:30:00.000Z
در مدل ذخیره می شود
در صورتی که معادل تاریخ میلادی
2018-02-07
باید باشد

**Comment by mrmashal** [comment]
مقدار
2018-02-06T20:30:00.000Z
معادل
UTC
ابتدای روز ۱۳۹۶/۱۱/۱۸ با توجه به سه ساعت و نیم اختلاف ساعت ایران هست
شما برای استخراج تاریخ از متغیر جاوااسکریپت، باید از کتابخانه
moment.js
استفاده کنید

**Comment by KarimFereidooni** [comment]
بله درسته با تبدیل تاریخ از
UTC
به
Local
مشکل حل شد
