### ISSUE TITLE
angular 6

### ISSUE THREAD

**Issue by omidkh68** [mrmashal/angular-material-persian-datepicker#4]
سلام 
خیلی ممنون از datepicker خوب تون
برنامه ای برای نسخه ۶ انگولار متریال ندارید؟

**Comment by mrmashal** [comment]
سلام. نه. ببنینین این بدردتون نمیخوره؟
https://github.com/fingerpich/jalali-angular-datepicker

**Comment by omidkh68** [comment]
@mrmashal 
ممنون بله بقیه رو دیدم
 منتهی برای شما چون کاملا همون متریال اصلی هستم میخواستم ببینم برای نسخه ۴ به بعد دارید یا خیر که متأسفانه  نیست
ممنون از جواب و وقتی که گذاشتین 🙏🌺
